# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\"[\n\x0b\x43hatRequest\x12\x11\n\tthread_id\x18\x01 \x01(\t\x12\x14\n\x0c\x66rom_user_id\x18\x02 \x01(\t\x12\x12\n\nto_user_id\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"\x1f\n\x0c\x43hatResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\",\n\x0b\x45rrorDetail\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t20\n\tChatAgent\x12#\n\x04\x43hat\x12\x0c.ChatRequest\x1a\r.ChatResponseB/\n com.dating.youjianxin.proto.chatB\tChatProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.dating.youjianxin.proto.chatB\tChatProtoP\001'
  _globals['_CHATREQUEST']._serialized_start=14
  _globals['_CHATREQUEST']._serialized_end=105
  _globals['_CHATRESPONSE']._serialized_start=107
  _globals['_CHATRESPONSE']._serialized_end=138
  _globals['_ERRORDETAIL']._serialized_start=140
  _globals['_ERRORDETAIL']._serialized_end=184
  _globals['_CHATAGENT']._serialized_start=186
  _globals['_CHATAGENT']._serialized_end=234
# @@protoc_insertion_point(module_scope)
