# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import user_pb2 as user__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserIdentityServiceStub(object):
    """=====================================================================
    2. UserIdentityService
    入参:已通过短信 / 三方授权 / 设备 ID 一次验证后的 identifier
    出参:userId(+ pending 标记)
    详见 dating-server/docs/user-info-service-design.md §5.2 §5.3
    =====================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveOrCreateByPhone = channel.unary_unary(
                '/UserIdentityService/ResolveOrCreateByPhone',
                request_serializer=user__pb2.ResolveOrCreateByPhoneRequest.SerializeToString,
                response_deserializer=user__pb2.ResolveOrCreateResponse.FromString,
                _registered_method=True)
        self.ResolveOrCreateByThirdParty = channel.unary_unary(
                '/UserIdentityService/ResolveOrCreateByThirdParty',
                request_serializer=user__pb2.ResolveOrCreateByThirdPartyRequest.SerializeToString,
                response_deserializer=user__pb2.ResolveOrCreateResponse.FromString,
                _registered_method=True)
        self.ResolveOrCreateByDevice = channel.unary_unary(
                '/UserIdentityService/ResolveOrCreateByDevice',
                request_serializer=user__pb2.ResolveOrCreateByDeviceRequest.SerializeToString,
                response_deserializer=user__pb2.ResolveOrCreateResponse.FromString,
                _registered_method=True)
        self.CheckBan = channel.unary_unary(
                '/UserIdentityService/CheckBan',
                request_serializer=user__pb2.CheckBanRequest.SerializeToString,
                response_deserializer=user__pb2.CheckBanResponse.FromString,
                _registered_method=True)


class UserIdentityServiceServicer(object):
    """=====================================================================
    2. UserIdentityService
    入参:已通过短信 / 三方授权 / 设备 ID 一次验证后的 identifier
    出参:userId(+ pending 标记)
    详见 dating-server/docs/user-info-service-design.md §5.2 §5.3
    =====================================================================
    """

    def ResolveOrCreateByPhone(self, request, context):
        """手机验证码登录后调用:解析或创建用户,更新 last_open_at
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveOrCreateByThirdParty(self, request, context):
        """三方授权登录后调用:解析或创建用户,更新 last_open_at
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveOrCreateByDevice(self, request, context):
        """设备 ID 快速登录:解析或创建用户,更新 last_open_at
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckBan(self, request, context):
        """查封禁状态(gateway 登录最后一步 + 业务侧兜底)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserIdentityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveOrCreateByPhone': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveOrCreateByPhone,
                    request_deserializer=user__pb2.ResolveOrCreateByPhoneRequest.FromString,
                    response_serializer=user__pb2.ResolveOrCreateResponse.SerializeToString,
            ),
            'ResolveOrCreateByThirdParty': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveOrCreateByThirdParty,
                    request_deserializer=user__pb2.ResolveOrCreateByThirdPartyRequest.FromString,
                    response_serializer=user__pb2.ResolveOrCreateResponse.SerializeToString,
            ),
            'ResolveOrCreateByDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveOrCreateByDevice,
                    request_deserializer=user__pb2.ResolveOrCreateByDeviceRequest.FromString,
                    response_serializer=user__pb2.ResolveOrCreateResponse.SerializeToString,
            ),
            'CheckBan': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBan,
                    request_deserializer=user__pb2.CheckBanRequest.FromString,
                    response_serializer=user__pb2.CheckBanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserIdentityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UserIdentityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserIdentityService(object):
    """=====================================================================
    2. UserIdentityService
    入参:已通过短信 / 三方授权 / 设备 ID 一次验证后的 identifier
    出参:userId(+ pending 标记)
    详见 dating-server/docs/user-info-service-design.md §5.2 §5.3
    =====================================================================
    """

    @staticmethod
    def ResolveOrCreateByPhone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserIdentityService/ResolveOrCreateByPhone',
            user__pb2.ResolveOrCreateByPhoneRequest.SerializeToString,
            user__pb2.ResolveOrCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveOrCreateByThirdParty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserIdentityService/ResolveOrCreateByThirdParty',
            user__pb2.ResolveOrCreateByThirdPartyRequest.SerializeToString,
            user__pb2.ResolveOrCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveOrCreateByDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserIdentityService/ResolveOrCreateByDevice',
            user__pb2.ResolveOrCreateByDeviceRequest.SerializeToString,
            user__pb2.ResolveOrCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckBan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserIdentityService/CheckBan',
            user__pb2.CheckBanRequest.SerializeToString,
            user__pb2.CheckBanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UserProfileServiceStub(object):
    """=====================================================================
    3. UserProfileService
    资料 + 兴趣 + 头像(三块合一,详见 dating-server/docs/user-info-service-design.md §5.2)
    =====================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProfile = channel.unary_unary(
                '/UserProfileService/GetProfile',
                request_serializer=user__pb2.GetProfileRequest.SerializeToString,
                response_deserializer=user__pb2.GetProfileResponse.FromString,
                _registered_method=True)
        self.BatchGetProfile = channel.unary_unary(
                '/UserProfileService/BatchGetProfile',
                request_serializer=user__pb2.BatchGetProfileRequest.SerializeToString,
                response_deserializer=user__pb2.BatchGetProfileResponse.FromString,
                _registered_method=True)
        self.UpdateProfile = channel.unary_unary(
                '/UserProfileService/UpdateProfile',
                request_serializer=user__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=user__pb2.UpdateProfileResponse.FromString,
                _registered_method=True)
        self.UpsertOnboarding = channel.unary_unary(
                '/UserProfileService/UpsertOnboarding',
                request_serializer=user__pb2.UpsertOnboardingRequest.SerializeToString,
                response_deserializer=user__pb2.UpsertOnboardingResponse.FromString,
                _registered_method=True)
        self.ReplaceUserInterests = channel.unary_unary(
                '/UserProfileService/ReplaceUserInterests',
                request_serializer=user__pb2.ReplaceUserInterestsRequest.SerializeToString,
                response_deserializer=user__pb2.ReplaceUserInterestsResponse.FromString,
                _registered_method=True)
        self.PresignAvatarUpload = channel.unary_unary(
                '/UserProfileService/PresignAvatarUpload',
                request_serializer=user__pb2.PresignAvatarUploadRequest.SerializeToString,
                response_deserializer=user__pb2.PresignAvatarUploadResponse.FromString,
                _registered_method=True)
        self.ConfirmAvatarUpload = channel.unary_unary(
                '/UserProfileService/ConfirmAvatarUpload',
                request_serializer=user__pb2.ConfirmAvatarUploadRequest.SerializeToString,
                response_deserializer=user__pb2.ConfirmAvatarUploadResponse.FromString,
                _registered_method=True)


class UserProfileServiceServicer(object):
    """=====================================================================
    3. UserProfileService
    资料 + 兴趣 + 头像(三块合一,详见 dating-server/docs/user-info-service-design.md §5.2)
    =====================================================================
    """

    def GetProfile(self, request, context):
        """单用户读取:默认返回主资料 + 兴趣 + 头像短期 URL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetProfile(self, request, context):
        """批量读取(≤200);Redis miss 后批量 DB 回填
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfile(self, request, context):
        """资料编辑(动态 SET,跳过未设置字段);MVP 仅 7 个标量
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertOnboarding(self, request, context):
        """onboarding 一次性写入完整资料 + 默认头像;gender/birthday 等定后不可改字段的唯一写入入口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplaceUserInterests(self, request, context):
        """全量替换兴趣标签;图片标签 ≤ 9,文字标签 ≤ 50
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PresignAvatarUpload(self, request, context):
        """头像 presigned PUT URL 签发(5 分钟有效)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmAvatarUpload(self, request, context):
        """客户端上传完调用:校验 + 更新 user_info.custom_avatar + 清缓存
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=user__pb2.GetProfileRequest.FromString,
                    response_serializer=user__pb2.GetProfileResponse.SerializeToString,
            ),
            'BatchGetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetProfile,
                    request_deserializer=user__pb2.BatchGetProfileRequest.FromString,
                    response_serializer=user__pb2.BatchGetProfileResponse.SerializeToString,
            ),
            'UpdateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfile,
                    request_deserializer=user__pb2.UpdateProfileRequest.FromString,
                    response_serializer=user__pb2.UpdateProfileResponse.SerializeToString,
            ),
            'UpsertOnboarding': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertOnboarding,
                    request_deserializer=user__pb2.UpsertOnboardingRequest.FromString,
                    response_serializer=user__pb2.UpsertOnboardingResponse.SerializeToString,
            ),
            'ReplaceUserInterests': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplaceUserInterests,
                    request_deserializer=user__pb2.ReplaceUserInterestsRequest.FromString,
                    response_serializer=user__pb2.ReplaceUserInterestsResponse.SerializeToString,
            ),
            'PresignAvatarUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.PresignAvatarUpload,
                    request_deserializer=user__pb2.PresignAvatarUploadRequest.FromString,
                    response_serializer=user__pb2.PresignAvatarUploadResponse.SerializeToString,
            ),
            'ConfirmAvatarUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmAvatarUpload,
                    request_deserializer=user__pb2.ConfirmAvatarUploadRequest.FromString,
                    response_serializer=user__pb2.ConfirmAvatarUploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UserProfileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserProfileService(object):
    """=====================================================================
    3. UserProfileService
    资料 + 兴趣 + 头像(三块合一,详见 dating-server/docs/user-info-service-design.md §5.2)
    =====================================================================
    """

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserProfileService/GetProfile',
            user__pb2.GetProfileRequest.SerializeToString,
            user__pb2.GetProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserProfileService/BatchGetProfile',
            user__pb2.BatchGetProfileRequest.SerializeToString,
            user__pb2.BatchGetProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserProfileService/UpdateProfile',
            user__pb2.UpdateProfileRequest.SerializeToString,
            user__pb2.UpdateProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertOnboarding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserProfileService/UpsertOnboarding',
            user__pb2.UpsertOnboardingRequest.SerializeToString,
            user__pb2.UpsertOnboardingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplaceUserInterests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserProfileService/ReplaceUserInterests',
            user__pb2.ReplaceUserInterestsRequest.SerializeToString,
            user__pb2.ReplaceUserInterestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PresignAvatarUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserProfileService/PresignAvatarUpload',
            user__pb2.PresignAvatarUploadRequest.SerializeToString,
            user__pb2.PresignAvatarUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmAvatarUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserProfileService/ConfirmAvatarUpload',
            user__pb2.ConfirmAvatarUploadRequest.SerializeToString,
            user__pb2.ConfirmAvatarUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UserRecommendationServiceStub(object):
    """=====================================================================
    4. UserRecommendationService(召回服务,服务于 match-service 的 D0/D1 队列生成)
    详见 dating-server/docs/match-service-prd-tech.md §4.1 / §4.2 / §6.7

    两个 RPC 设计上"无状态 + 无 user-side 缓存":每次调用即查 DB,
    由调用方(match-service)按需多次调用做分层(L0~L3)。
    RPC 本身不感知层级,只负责按入参做单次过滤召回 + 排序。

    单表无 JOIN 原则:本服务的查询不与 geo_city 等表 JOIN,
    city_id 等关联在 service 层完成。
    =====================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDhCandidates = channel.unary_unary(
                '/UserRecommendationService/ListDhCandidates',
                request_serializer=user__pb2.ListDhCandidatesRequest.SerializeToString,
                response_deserializer=user__pb2.ListDhCandidatesResponse.FromString,
                _registered_method=True)
        self.NearbyUsers = channel.unary_unary(
                '/UserRecommendationService/NearbyUsers',
                request_serializer=user__pb2.NearbyUsersRequest.SerializeToString,
                response_deserializer=user__pb2.NearbyUsersResponse.FromString,
                _registered_method=True)
        self.PickDhCitiesForCaller = channel.unary_unary(
                '/UserRecommendationService/PickDhCitiesForCaller',
                request_serializer=user__pb2.PickDhCitiesForCallerRequest.SerializeToString,
                response_deserializer=user__pb2.PickDhCitiesForCallerResponse.FromString,
                _registered_method=True)


class UserRecommendationServiceServicer(object):
    """=====================================================================
    4. UserRecommendationService(召回服务,服务于 match-service 的 D0/D1 队列生成)
    详见 dating-server/docs/match-service-prd-tech.md §4.1 / §4.2 / §6.7

    两个 RPC 设计上"无状态 + 无 user-side 缓存":每次调用即查 DB,
    由调用方(match-service)按需多次调用做分层(L0~L3)。
    RPC 本身不感知层级,只负责按入参做单次过滤召回 + 排序。

    单表无 JOIN 原则:本服务的查询不与 geo_city 等表 JOIN,
    city_id 等关联在 service 层完成。
    =====================================================================
    """

    def ListDhCandidates(self, request, context):
        """召回 DH 候选(D0/D1 共用)
        match-service 端调用方按 L0~L3 分层多次调用,每层 limit = 240 - 已累积,累积去重直到 240
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NearbyUsers(self, request, context):
        """召回 BH 候选(D0/D1 共用)
        Phase 1 实现:city_id 相等(同城)过滤;radius_km 入参保留但 Phase 1 忽略,Phase 2 升级 Redis GEO 后启用
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PickDhCitiesForCaller(self, request, context):
        """给 match-service 用:为指定 caller 的 DH 候选生成"同 state 不同 city"的位置覆盖
        业务诉求:DH 不存真实居住地;每次出卡时让 DH 的 state 跟 caller 一致、city 跟 caller 不同,
        既能本地化展示又避免穿帮。本 RPC 只算覆盖值,不写库。
        service 层逻辑:
        1) 读 caller 的 state_code / city_id;caller 未填位置 → 返回空 map(前端不渲染位置)
        2) 从 geo_city 字典取该 state 下 city_id != caller.city_id 的城市列表(L1 Caffeine 缓存)
        3) 对每个 dh_user_id,用 hash(dh_user_id, caller_user_id) 作 seed 从列表里确定性挑 1 个
        同一 (caller, dh) 跨次稳定;不同 caller 看到同一 DH 可能在不同 city
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserRecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDhCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDhCandidates,
                    request_deserializer=user__pb2.ListDhCandidatesRequest.FromString,
                    response_serializer=user__pb2.ListDhCandidatesResponse.SerializeToString,
            ),
            'NearbyUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.NearbyUsers,
                    request_deserializer=user__pb2.NearbyUsersRequest.FromString,
                    response_serializer=user__pb2.NearbyUsersResponse.SerializeToString,
            ),
            'PickDhCitiesForCaller': grpc.unary_unary_rpc_method_handler(
                    servicer.PickDhCitiesForCaller,
                    request_deserializer=user__pb2.PickDhCitiesForCallerRequest.FromString,
                    response_serializer=user__pb2.PickDhCitiesForCallerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserRecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UserRecommendationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserRecommendationService(object):
    """=====================================================================
    4. UserRecommendationService(召回服务,服务于 match-service 的 D0/D1 队列生成)
    详见 dating-server/docs/match-service-prd-tech.md §4.1 / §4.2 / §6.7

    两个 RPC 设计上"无状态 + 无 user-side 缓存":每次调用即查 DB,
    由调用方(match-service)按需多次调用做分层(L0~L3)。
    RPC 本身不感知层级,只负责按入参做单次过滤召回 + 排序。

    单表无 JOIN 原则:本服务的查询不与 geo_city 等表 JOIN,
    city_id 等关联在 service 层完成。
    =====================================================================
    """

    @staticmethod
    def ListDhCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserRecommendationService/ListDhCandidates',
            user__pb2.ListDhCandidatesRequest.SerializeToString,
            user__pb2.ListDhCandidatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NearbyUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserRecommendationService/NearbyUsers',
            user__pb2.NearbyUsersRequest.SerializeToString,
            user__pb2.NearbyUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PickDhCitiesForCaller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UserRecommendationService/PickDhCitiesForCaller',
            user__pb2.PickDhCitiesForCallerRequest.SerializeToString,
            user__pb2.PickDhCitiesForCallerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
