# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vision.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'vision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvision.proto\x12\x06vision\"7\n\x11UnderstandRequest\x12\x12\n\nimage_urls\x18\x01 \x03(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\"%\n\x12UnderstandResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"&\n\x10ScoreFaceRequest\x12\x12\n\nimage_urls\x18\x01 \x03(\t\"\\\n\x11ScoreFaceResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x12\n\nappearance\x18\x02 \x01(\x05\x12#\n\x1bsexual_attractiveness_score\x18\x03 \x01(\x05\"/\n\x1a\x41nalyzeProfilePhotoRequest\x12\x11\n\timage_url\x18\x01 \x01(\t\"/\n\x1b\x41nalyzeProfilePhotoResponse\x12\x10\n\x08\x61nalysis\x18\x01 \x01(\t\",\n\x0b\x45rrorDetail\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf4\x01\n\x0bVisionAgent\x12\x43\n\nUnderstand\x12\x19.vision.UnderstandRequest\x1a\x1a.vision.UnderstandResponse\x12@\n\tScoreFace\x12\x18.vision.ScoreFaceRequest\x1a\x19.vision.ScoreFaceResponse\x12^\n\x13\x41nalyzeProfilePhoto\x12\".vision.AnalyzeProfilePhotoRequest\x1a#.vision.AnalyzeProfilePhotoResponseB3\n\"com.dating.youjianxin.proto.visionB\x0bVisionProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.dating.youjianxin.proto.visionB\013VisionProtoP\001'
  _globals['_UNDERSTANDREQUEST']._serialized_start=24
  _globals['_UNDERSTANDREQUEST']._serialized_end=79
  _globals['_UNDERSTANDRESPONSE']._serialized_start=81
  _globals['_UNDERSTANDRESPONSE']._serialized_end=118
  _globals['_SCOREFACEREQUEST']._serialized_start=120
  _globals['_SCOREFACEREQUEST']._serialized_end=158
  _globals['_SCOREFACERESPONSE']._serialized_start=160
  _globals['_SCOREFACERESPONSE']._serialized_end=252
  _globals['_ANALYZEPROFILEPHOTOREQUEST']._serialized_start=254
  _globals['_ANALYZEPROFILEPHOTOREQUEST']._serialized_end=301
  _globals['_ANALYZEPROFILEPHOTORESPONSE']._serialized_start=303
  _globals['_ANALYZEPROFILEPHOTORESPONSE']._serialized_end=350
  _globals['_ERRORDETAIL']._serialized_start=352
  _globals['_ERRORDETAIL']._serialized_end=396
  _globals['_VISIONAGENT']._serialized_start=399
  _globals['_VISIONAGENT']._serialized_end=643
# @@protoc_insertion_point(module_scope)
