# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import vision_pb2 as vision__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vision_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VisionAgentStub(object):
    """图像 agent：图像理解 / 颜值打分 / 头像分析
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Understand = channel.unary_unary(
                '/vision.VisionAgent/Understand',
                request_serializer=vision__pb2.UnderstandRequest.SerializeToString,
                response_deserializer=vision__pb2.UnderstandResponse.FromString,
                _registered_method=True)
        self.ScoreFace = channel.unary_unary(
                '/vision.VisionAgent/ScoreFace',
                request_serializer=vision__pb2.ScoreFaceRequest.SerializeToString,
                response_deserializer=vision__pb2.ScoreFaceResponse.FromString,
                _registered_method=True)
        self.AnalyzeProfilePhoto = channel.unary_unary(
                '/vision.VisionAgent/AnalyzeProfilePhoto',
                request_serializer=vision__pb2.AnalyzeProfilePhotoRequest.SerializeToString,
                response_deserializer=vision__pb2.AnalyzeProfilePhotoResponse.FromString,
                _registered_method=True)


class VisionAgentServicer(object):
    """图像 agent：图像理解 / 颜值打分 / 头像分析
    """

    def Understand(self, request, context):
        """图像理解：按 prompt 对一张/多张图片做自然语言理解
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScoreFace(self, request, context):
        """颜值打分：对一张/多张图片打分（多图取平均），返回结构化分数
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeProfilePhoto(self, request, context):
        """头像/资料照分析：返回 "描述 | 风格标签" / not_human / anime_human
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisionAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Understand': grpc.unary_unary_rpc_method_handler(
                    servicer.Understand,
                    request_deserializer=vision__pb2.UnderstandRequest.FromString,
                    response_serializer=vision__pb2.UnderstandResponse.SerializeToString,
            ),
            'ScoreFace': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreFace,
                    request_deserializer=vision__pb2.ScoreFaceRequest.FromString,
                    response_serializer=vision__pb2.ScoreFaceResponse.SerializeToString,
            ),
            'AnalyzeProfilePhoto': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeProfilePhoto,
                    request_deserializer=vision__pb2.AnalyzeProfilePhotoRequest.FromString,
                    response_serializer=vision__pb2.AnalyzeProfilePhotoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vision.VisionAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vision.VisionAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VisionAgent(object):
    """图像 agent：图像理解 / 颜值打分 / 头像分析
    """

    @staticmethod
    def Understand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vision.VisionAgent/Understand',
            vision__pb2.UnderstandRequest.SerializeToString,
            vision__pb2.UnderstandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScoreFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vision.VisionAgent/ScoreFace',
            vision__pb2.ScoreFaceRequest.SerializeToString,
            vision__pb2.ScoreFaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeProfilePhoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vision.VisionAgent/AnalyzeProfilePhoto',
            vision__pb2.AnalyzeProfilePhotoRequest.SerializeToString,
            vision__pb2.AnalyzeProfilePhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
